version: "3.9"

networks:
  backend:

services:
  regex_backend_web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bash -c "bundle install --path vendor/bundle && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      FIRESTORE_EMULATOR_HOST: 'regex_backend_firebase:8080'
      GCP_AUTH_KEY_FILE: 'service_account.json'
      GCP_PROJECT_ID: 'regex-bc723'
      REGX_LANGUAGE: 'Ruby'
      REGX_LANGUAGE_VERSION: '3.1.2'
    ports:
      - "3000:3000"
    networks:
      - backend
  regex_backend_firebase:
    build:
      context: .
      dockerfile: docker/firebase/Dockerfile
    hostname: regex_backend_firebase
    volumes:
      - ./firebase/emulators/:/opt/workspace:cached
      - ./firebase/bin/:/root/.cache:cached
      - ./firebase/config/:/root/.config:cached
    ports:
      - 4000:4000 # Emulator Suite UI
      - 5002:5000 # Firebase Hosting
      - 5001:5001 # Clound Functions
      - 9000:9000 # Realtime Database
      - 8080:8080 # Cloud Firestore
      - 8085:8085 # Cloud Pub/Sub
    working_dir: /opt/workspace
    networks:
      - backend
    #    command: bash -c "/bin/bash"
    command: bash -c "firebase emulators:start --import=./data --export-on-exit"
    tty: true
